apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.claimName }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2.5Gi
